spring:
  docker:
    compose:
      skip:
        in-tests: false
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update                          # 애플리케이션 실행 시 DB 스키마 자동 업데이트
    properties:
      org.hibernate.envers.store_data_at_delete: true # envers가 삭제도 상세하게 기록하게함.
      hibernate:
        show_sql: false
        format_sql: true                        # 출력되는 SQL 쿼리를 보기 좋게 포맷팅
        highlight_sql: true                     # 콘솔에서 SQL 쿼리를 하이라이트 처리 (색상)

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.hibernate.SQL: DEBUG                   # Hibernate SQL 쿼리 출력
    org.hibernate.orm.jdbc.bind: TRACE         # Hibernate SQL 파라미터 바인딩 출력
    org.springframework.jdbc.core: DEBUG       # Spring JDBC Template 쿼리 실행 로그
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE  # PreparedStatement 파라미터 바인딩 상세 로그

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: study-commerce-server
